## Rubric

Instructions: DELETE this cell before you submit via a `git push` to your repo before deadline. This cell is for your reference only and is not needed in your report. 

 Scoring: Out of 10 points

- Each Developing  => -2 pts
- Each Unsatisfactory/Missing => -4 pts
  - until the score is 0

If students address the detailed feedback in a future checkpoint they will earn these points back






|                                  | **Unsatisfactory**                                                                                                                                                                                                                                                                                                                        | **Developing**                                                                                                                                                                                                       | **Proficient**                                                                                                                                                                                            | **Excellent**                                                                                                                                                                            |
|----------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **EDA relevance**                | EDA is mostly neither relevant to the question nor helpful in figuring out how to address the question. Or the EDA does address the question, but many obviously relevant variables / analyses / figures were not included. | EDA is partly irrelevant/unhelpful. EDA missed one or two obvioulsy relevant analysis (distributions of single variables or relationships between variables) | EDA includes the obviously relevant / helpful variables in addressing the question.                                                              | Thorough EDA fully explored the dataset                                                                                                                 |
| **EDA analysis and description** | Many of the analyses are poor choices (e.g., using means instead of medians for obviously skewed data), or are poorly described in the text, or do not aid understanding the data                                                                                                                                                     | Some of the analyses are poor choices, or are poorly described in the text, or do not aid understanding the data                                                                                                 | All analyses are correct choices. Only one or two have minor issues in the text descriptions supporting them. Mostly they fit well with other elements of the EDA and support understanding the data  | All analyses are correct choices with clear text descriptions supporting them. The figures fit well with the other elements of the EDA, producing a clear understanding of the data. |
| **EDA figures**                  | Many of the figures are poor plot choices (e.g., using a bar plot to represent a time series where it would be better to use a line plot) or have poor aesthetics (including colormap, data point shape/color, axis labels, titles, annotations, text legibility) or do not aid understanding the data                                | Some of the figures are poor plot choices or have poor aesthetics. Some figures do not aid understanding the data                                                                                                | All figures are correct plot choices. Only one or two have minor questionable aesthetic choices. The figures mostly fit well with the other elements of the EDA and support understanding the data    | All figures are correct plot choices with beautiful aesthetics. The figures fit well with the other elements of the EDA, producing a clear understanding of the data.                |

# COGS 108 - EDA Checkpoint

## Authors

Instructions: REPLACE the contents of this cell with your team list and their contributions. Note that this will change over the course of the checkpoints

This is a modified [CRediT taxonomy of contributions](https://credit.niso.org). For each group member please list how they contributed to this project using these terms:
> Analysis, Background research, Conceptualization, Data curation, Experimental investigation, Methodology, Project administration, Software, Visualization, Writing – original draft, Writing – review & editing

Example team list and credits:
- Alice Anderson: Conceptualization, Data curation, Methodology, Writing - original draft
- Bob Barker:  Analysis, Software, Visualization
- Charlie Chang: Project administration, Software, Writing - review & editing
- Dani Delgado: Analysis, Background research, Visualization, Writing - original draft

# Research Question

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Background and Prior Work

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

# Hypothesis

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Data

### Data overview

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your data checkpoint feedback

In [ ]:
# Run this code every time when you're actively developing modules in .py files.  It's not needed if you aren't making modules
#
## this code is necessary for making sure that any modules we load are updated here 
## when their source code .py files are modified

%load_ext autoreload
%autoreload 2

In [ ]:
# Setup code -- Run only once after cloning!!! 
#
# this code downloads the data from its source to the `data/00-raw/` directory
# if the data hasn't updated you don't need to do this again!

# if you don't already have these packages (you should!) uncomment this line
# %pip install requests tqdm

import sys
sys.path.append('./modules') # this tells python where to look for modules to import

import get_data # this is where we get the function we need to download data

# replace the urls and filenames in this list with your actual datafiles
# yes you can use Google drive share links or whatever
# format is a list of dictionaries; 
# each dict has keys of 
#   'url' where the resource is located
#   'filename' for the local filename where it will be stored 
datafiles = [
    { 'url': 'https://raw.githubusercontent.com/fivethirtyeight/data/refs/heads/master/airline-safety/airline-safety.csv', 'filename':'airline-safety.csv'},
    { 'url': 'https://raw.githubusercontent.com/fivethirtyeight/data/refs/heads/master/bad-drivers/bad-drivers.csv', 'filename':'bad-drivers.csv'}
]

get_data.get_raw(datafiles,destination_directory='data/00-raw/')

### Dataset #1 

Instructions: REPLACE the contents of this cell and the one below with your work, including any updates to recover points lost in your data checkpoint feedback

In [ ]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

### Dataset #2
 as above, add any more copies of this that you need to given how many datasets you have

## Results

### Exploratory Data Analysis

Instructions: replace the words in this subsection with whatever words you need to setup and preview the EDA you're going to do.   

Please explicitly load the fully wrangled data you will use from `data/02-processed`.  This is a good idea rather than forcing people to re-run the data getting / wrangling cells above.  Sometimes it takes a long time to get / wrangle data compared to reloading the fixed up dataset.

Carry out whatever EDA you need to for your project in the code cells below.  Because every project will be different we can't really give you much of a template at this point. But please make sure you describe the what and why in text here as well as providing interpretation of results and context.

Please note that you should consider the use of python modules in your work.  Any code which gets called repeatedly should be modularized. So if you run the same pre-processing, analysis or visualiazation on different subsets of the data, then you should turn that into a function or class.  Put that function or class in a .py file that lives in `modules/`.  Import the module you made and use it to get your work done.  For reference see `get_raw()` which is inside `modules/get_data.py`.

#### Section 1 of EDA - please give it a better title than this

Some more words and stuff.  Remember notebooks work best if you interleave the code that generates a result with properly annotate figures and text that puts these results into context.

In [29]:
import pandas as pd
import numpy as np
from scipy import stats
from IPython.display import display

In [30]:
data=pd.read_csv('data/02-processed/nhis_2024_sample_adult_cleaned.csv')
data.head()

,HHX,WTFA_A,PSTRAT,PPSU,AGEP_A,sex,race_ethnicity,race_group,education,POVRATTC_A,health_insurance,housing_tenure,usual_place_care,transportation_barrier,housing_cost_trouble,general_health,government_rent_assistance,delayed_medical_care,any_er_visit,doctor_gap_yr
0,H067658,5780.565,122,2,49,Male,White non-Hispanic,White only,AA academic,2.82,Uninsured,Owned or being bought,No single usual place,0.0,0.0,5.0,-1.0,0.0,0.0,5.0
1,H076577,3994.244,122,2,53,Male,White non-Hispanic,White only,AA academic,2.01,Insured,Rented,Has usual place of care,1.0,0.0,4.0,0.0,0.0,2.0,1.0
2,H019335,6636.755,122,2,82,Male,White non-Hispanic,White only,AA academic,1.90,Insured,Rented,Has usual place of care,0.0,0.0,4.0,0.0,0.0,0.0,1.0
3,H012701,13767.420,122,2,42,Male,White non-Hispanic,White only,"Some college, no degree",4.48,Insured,Owned or being bought,Has usual place of care,0.0,0.0,3.0,-1.0,0.0,0.0,2.0
4,H049678,18880.030,115,1,38,Female,Black non-Hispanic,Black only,Professional,6.37,Insured,Rented,Has usual place of care,0.0,0.0,3.0,0.0,0.0,1.0,1.0

In [31]:
def chi_square(predictor,outcome,d):
    contingency=pd.crosstab(d[predictor],d[outcome])
    chi2, p_value, dof, expected = stats.chi2_contingency(contingency)
    print(predictor,'---',outcome)
    display(contingency)
    print('Chi square statistics: ',chi2)
    print('p_value: ', p_value)
    print('degree of freedom: ', dof)
    print('expected: ', expected)
    print('\n')

chi_square('housing_tenure','usual_place_care',data)
chi_square('housing_tenure','general_health',data)
chi_square('housing_tenure','delayed_medical_care',data)
chi_square('housing_tenure','any_er_visit',data)
chi_square('housing_tenure','doctor_gap_yr',data)

housing_tenure --- usual_place_care

usual_place_care,Has usual place of care,No single usual place,No usual place
housing_tenure,,,
Other arrangement,490,64,12
Owned or being bought,18558,1068,434
Rented,6996,1101,194

Chi square statistics:  535.1069909492751
p_value:  1.7061771090264127e-114
degree of freedom:  4
expected:  [[5.09766020e+02 4.37070927e+01 1.25268873e+01]
 [1.80669724e+04 1.54905350e+03 4.43974133e+02]
 [7.46726161e+03 6.40239409e+02 1.83498980e+02]]


housing_tenure --- general_health

general_health         1.0   2.0   3.0   4.0   5.0
housing_tenure
Other arrangement       43   102   196   154    71
Owned or being bought  623  2246  6066  7246  3879
Rented                 386  1319  2523  2479  1584

Chi square statistics:  270.7502290171913
p_value:  6.814897174193076e-54
degree of freedom:  8
expected:  [[  20.591071     71.77514957  171.95110143  193.3642494   108.31842861]
 [ 729.78248089 2543.83303939 6094.23868313 6853.15696649 3838.9888301 ]
 [ 301.62644811 1051.39181105 2518.81021544 2832.47878411 1586.69274129]]


housing_tenure --- delayed_medical_care

delayed_medical_care     0.0   1.0
housing_tenure
Other arrangement        506    60
Owned or being bought  18841  1219
Rented                  7345   946

Chi square statistics:  241.7959388022155
p_value:  3.1237697559371135e-53
degree of freedom:  2
expected:  [[  522.44949338    43.55050662]
 [18516.49617872  1543.50382128]
 [ 7653.0543279    637.9456721 ]]


housing_tenure --- any_er_visit

any_er_visit             0.0   1.0  2.0  3.0  4.0
housing_tenure
Other arrangement        405    92   39   12   18
Owned or being bought  16162  2673  775  246  204
Rented                  6172  1289  492  149  189

Chi square statistics:  211.32616033149452
p_value:  2.6128451663379016e-41
degree of freedom:  8
expected:  [[4.45076391e+02 7.93500017e+01 2.55626794e+01 7.96631739e+00
  8.04461044e+00]
 [1.57742622e+04 2.81229865e+03 9.05984715e+02 2.82339800e+02
  2.85114638e+02]
 [6.51966141e+03 1.16235135e+03 3.74452606e+02 1.16693882e+02
  1.17840751e+02]]


housing_tenure --- doctor_gap_yr

doctor_gap_yr          0.0    1.0   2.0  3.0  4.0  5.0  6.0
housing_tenure
Other arrangement        2    480    39   18   14    7    6
Owned or being bought   14  18035  1032  314  286  198  181
Rented                  24   6851   717  262  208  141   88

Chi square statistics:  318.9073654695723
p_value:  4.98750630234959e-61
degree of freedom:  12
expected:  [[7.82930456e-01 4.96495349e+02 3.49969914e+01 1.16265173e+01
  9.94321679e+00 6.77234845e+00 5.38264689e+00]
 [2.77483833e+01 1.75966373e+04 1.24035273e+03 4.12063492e+02
  3.52404468e+02 2.40023516e+02 1.90770135e+02]
 [1.14686862e+01 7.27286738e+03 5.12650275e+02 1.70309991e+02
  1.45652315e+02 9.92041360e+01 7.88472179e+01]]

In [32]:
data_drop_other=data[data['housing_tenure']!='Other arrangement']
chi_square('housing_tenure','usual_place_care',data_drop_other)
chi_square('housing_tenure','general_health',data_drop_other)
chi_square('housing_tenure','delayed_medical_care',data_drop_other)
chi_square('housing_tenure','any_er_visit',data_drop_other)
chi_square('housing_tenure','doctor_gap_yr',data_drop_other)

housing_tenure --- usual_place_care

usual_place_care,Has usual place of care,No single usual place,No usual place
housing_tenure,,,
Owned or being bought,18558,1068,434
Rented,6996,1101,194

Chi square statistics:  529.1569769856063
p_value:  1.2445788523834243e-115
degree of freedom:  2
expected:  [[18080.9579909   1534.69507248   444.34693662]
 [ 7473.0420091    634.30492752   183.65306338]]


housing_tenure --- general_health

general_health         1.0   2.0   3.0   4.0   5.0
housing_tenure
Owned or being bought  623  2246  6066  7246  3879
Rented                 386  1319  2523  2479  1584

Chi square statistics:  209.63750012698526
p_value:  3.1794930115127106e-44
degree of freedom:  4
expected:  [[ 713.92684561 2522.44717999 6077.22267292 6881.0094882  3865.39381327]
 [ 295.07315439 1042.55282001 2511.77732708 2843.9905118  1597.60618673]]


housing_tenure --- delayed_medical_care

delayed_medical_care     0.0   1.0
housing_tenure
Owned or being bought  18841  1219
Rented                  7345   946

Chi square statistics:  235.81124820526725
p_value:  3.2216124473925363e-53
degree of freedom:  1
expected:  [[18528.13516278  1531.86483722]
 [ 7657.86483722   633.13516278]]


housing_tenure --- any_er_visit

any_er_visit             0.0   1.0  2.0  3.0  4.0
housing_tenure
Owned or being bought  16162  2673  775  246  204
Rented                  6172  1289  492  149  189

Chi square statistics:  186.146839866604
p_value:  3.566105963638228e-39
degree of freedom:  4
expected:  [[15802.61860252  2803.34803005   896.47702021   279.48573243
    278.07061479]
 [ 6531.38139748  1158.65196995   370.52297979   115.51426757
    114.92938521]]


housing_tenure --- doctor_gap_yr

doctor_gap_yr          0.0    1.0   2.0  3.0  4.0  5.0  6.0
housing_tenure
Owned or being bought   14  18035  1032  314  286  198  181
Rented                  24   6851   717  262  208  141   88

Chi square statistics:  312.6640883338678
p_value:  1.5793478487938012e-64
degree of freedom:  6
expected:  [[2.68872350e+01 1.76083087e+04 1.23752037e+03 4.07553878e+02
  3.49534055e+02 2.39862439e+02 1.90333322e+02]
 [1.11127650e+01 7.27769130e+03 5.11479630e+02 1.68446122e+02
  1.44465945e+02 9.91375613e+01 7.86666784e+01]]

#### Section 2 of EDA if you need it  - please give it a better title than this

Some more words and stuff.  Remember notebooks work best if you interleave the code that generates a result with properly annotate figures and text that puts these results into context.

In [ ]:
## YOUR CODE HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

## Ethics

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Team Expectations

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Project Timeline Proposal

Instructions: Replace this with your timeline.  **PLEASE UPDATE your Timeline!** No battle plan survives contact with the enemy, so make sure we understand how your plans have changed.  Also if you have lost points on the previous checkpoint fix them